# سوال زرد
# ID : 2885
# https://quera.ir/problemset/contest/3537/%D8%B3%D8%A4%D8%A7%D9%84-%D9%BE%DB%8C%D8%A7%D8%AF%D9%87-%D8%B3%D8%A7%D8%B2%DB%8C-%D8%B3%D9%88%D8%A7%D9%84-%D8%B2%D8%B1%D8%AF
# https://b2n.ir/222646

i = int(input())
print(f'W{"o" * i}w!')

###########################################################

i = int(input())
string = "W" + "o" * i + "w!"
print(string)

###########################################################

i = int(input())
print('W{}w!'.format("o" * i))
