# تاریخ تولد
# ID : 615
# https://quera.ir/problemset/university/615/%D8%B3%D8%A4%D8%A7%D9%84-%D8%AF%D8%A7%D9%86%D8%B4%DA%AF%D8%A7%D9%87-%D8%B5%D9%86%D8%B9%D8%AA%DB%8C-%D8%B4%D8%B1%DB%8C%D9%81-%D9%85%D8%A8%D8%A7%D9%86%DB%8C-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D9%87%D9%86%D9%88%DB%8C%D8%B3%DB%8C-%D9%BE%D8%A7%DB%8C%DB%8C%D8%B2-%DB%B9%DB%B3-%D8%AA%D8%A7%D8%B1%DB%8C%D8%AE-%D8%AA%D9%88%D9%84%D8%AF
# https://b2n.ir/815094

string = input()
print(f'saal:{string[:2]}\nmaah:{string[2:]}')

###########################################################

string = input()
print('saal:{0}\nmaah:{1}'.format(string[:2], string[2:]))

###########################################################

string = input()
saal = string[:2]
maah = string[2:]

print('saal:%s\nmaah:%s' % (saal, maah))
